package hr.fer.zemris.java.tecaj.hw5.db.lexer;

/**
 * A {@code Token} that is generated by the {@code Lexer}. The {@code Token} can
 * be one of the following types, as defined in the {@link TokenType}:
 * <ul>
 * <li><strong>SYMBOL</strong> used to represent a symbol.</li>
 * <li><strong>OPERATOR</strong> used to represent a comparison operator.</li>
 * <li><strong>STRING_LITERAL</strong> used to represent a string literal.</li>
 * <li><strong>COMMAND</strong> used to represent a command or field name.</li>
 * <li><strong>EOF</strong> used to represent the end of file.</li>
 * </ul>
 * 
 * @author Kristijan Vulinovic
 *
 */
public class Token {
	/** The value stored in this token. */
	private final Object value;
	/** The type of this token. */
	private final TokenType type;

	/**
	 * Creates a new {@code Token} of the given type with the given value.
	 * 
	 * @param value
	 *            the value to be stored in this token.
	 * @param type
	 *            the type of this token.
	 */
	public Token(Object value, TokenType type) {
		super();
		this.value = value;
		this.type = type;
	}

	/**
	 * Returns the value of this {@code Token}.
	 * 
	 * @return the value of this {@code Token}.
	 */
	public Object getValue() {
		return value;
	}

	/**
	 * Returns the type of the {@code Token}.
	 * 
	 * @return the type of the {@code Token}.
	 */
	public TokenType getType() {
		return type;
	}
}
